apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "guacamole.fullname" . }}-configuration
data:
{{- range $key, $val := .Values.guacamole.configurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
  user-mapping.xml: |-
    <user-mapping>
      
        <!-- Per-user authentication and config information -->
        <authorize username="admin" password={{ .Values.global.adminPassword | quote }}>
            <protocol>ssh</protocol>
            <param name="hostname">{{ .Values.guacamole.ssh.host }}</param>
            <param name="port">{{ .Values.guacamole.ssh.port }}</param>
            <param name="username">{{ .Values.guacamole.ssh.user }}</param>
            <param name="password">{{ .Values.guacamole.ssh.password }}</param>
        </authorize>
    
    </user-mapping>
